name: Newman Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  run-newman:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run Newman collection
        run: npx newman run Dojo.postman_collection.json -r htmlextra --reporter-htmlextra-export newman/report.html

      - name: Upload HTML report
        uses: actions/upload-artifact@v4
        with:
          name: newman-html-report
          path: newman/report.html
